[workspace]
resolver = "2"

members = [
  "lucile-core",
  "database",
  "search",
  "app",
  "cli",
  "gui",
]

[profile.dev.package.sqlx-macros]
opt-level = 3

[profile.dev.build-override]
opt-level=3
codegen-units=1

