[package]
name = "search"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lucille-core = {path = "../lucille-core"}

log = "0.4"
tantivy = "0.16"
thiserror = "1.0"
