[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"

walkdir = "2.3"

rayon = "1"

anyhow = "1"
thiserror = "1"
