[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lucile-core = {path = "../lucile-core"}
database = {path = "../database"}

log = "0.4"
thiserror = "1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1"

walkdir = "2.3"
rayon = "1"

subrip = "0.1.0"
encoding_rs = "0.8.26"
torrent-name-parser = "0.5.0"
sha2 = "0.9"
